# Generated by Django 5.2.3 on 2025-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_add_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
