# Generated by Django 5.2.3 on 2025-06-16 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_party_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='constituency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='candidate_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
