# Generated by Django 5.2.3 on 2025-06-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidate_votes_alter_candidate_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.constituency'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.county'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.party'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.position'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.ward'),
        ),
    ]
