# Generated by Django 5.2.3 on 2025-06-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_candidate_constituency_alter_candidate_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
    ]
