# Generated by Django 5.2.3 on 2025-06-18 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_candidate_bio_alter_candidate_manifesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='party_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
